### ISSUE TITLE
AgriCraft: Mystical Flower Seed Mutation Crashing

### ISSUE THREAD

**Issue by Azikai** [jadedcat/AS2Configs#217]
Whilst trying to mutate Mystical White Flower Seeds and Mystical Blue Flower Seeds to make Mystical Light Blue Flower Seeds, I crash.

I don't crash when I get weeds, but when I seem to get my Light Blue Flower, I crash.

Here is the crash report:
http://pastebin.com/FLnfYJ1q

Now, I am not certain, but I think it's Agricraft....
```
-- Possibly involved mods --
Details:
    AgriCraft: <snip>
    AgriCraft: <snip>
    AgriCraft: <snip>
    AgriCraft: <snip>
    AgriCraft: <snip>
    AgriCraft: <snip>
    AgriCraft: <snip>
    AgriCraft: <snip>
```
